const organizations = [
  {
    name: "Tranquility Hospital and Research Centre",
    specialization: "Specialist Neuro-psychiatric Hospital",
    isOrganization: true,
    category: "psychotherapy",
    OpeningHours: "24 hours Emergency",
    location: "Khumaltar Oralo, Lalitpur",
    email: "info.tranquilityhospital@gmail.com",
    phoneNumber: "9841504122",
  },
  {
    name: "TPO Nepal",
    specialization: "Physchosocial Mental Health Service",
    isOrganization: true,
    category: "Psychotherapy",
    OpeningHours: "9am - 5pm Monday - Friday",
    location: "Baluwatar, Kathmandu",
    email: "tponepal@tponepal.org",
    phoneNumber: "014431717",
  },
  {
    name: "Centre for Mental Health & Counselling - Nepal (CMC-Nepal)",
    specialization: "Mental Health and Psychosocial Service",
    isOrganization: true,
    category: "Psychotherapy",
    OpeningHours: "Sunday - Friday by appointment",
    location: "Thapathali Heights, Kathmandu",
    email: "cmcnepal@mos.com.np",
    phoneNumber: "4102037",
  },
  {
    name: "Mano Spandan Nepal",
    specialization:
      "Learning centre for special needs children, counselling, psychotherapy and training for parents, teachers, students and other professionals",
    isOrganization: true,
    category: "psychotherapy",
    OpeningHours: "10 am - 5 pm from Sunday - Friday",
    location: "Bijulibazar, Bhadrabinayak Marg, Kathmandu",
    phoneNumber: "01-5244878",
  },
  {
    name: "Psychbigyaan Network Nepal - PNN",
    specialization: "Mental Health",
    isOrganization: true,
    category: "Psychotherapy",
    OpeningHours: "11:30 am - 6:00 pm from Monday - Saturday",
    location: ["Dhobighat", " Lalitpur"],
    phoneNumber: "9860937293",
  },
  {
    name: "Dr Sagun Ballav Pant",
    specialization: "MD Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Institute of Medicine, TU Teaching Hospital",
    email: "sagum055@gmail.com",
    phoneNumber: "9841444410",
  },
  {
    name: "Dr Anurag Misra",
    specialization: "Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Grande International Hospital",
    email: "anuragmisra555@gmail.com",
    phoneNumber: "015159266",
  },
  {
    name: "Dr Pradeep Pandey",
    specialization: "MBBS, MD, Post Graduate of Doctor in Clinical Psychology",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Alka Hospital, Jawalakhel Kathmandu",
    email: "pradeep-sant1@hotmail.com",
    phoneNumber: "9841741929",
  },
  {
    name: "Dr. Sandarba Adhikari",
    specialization: "MD Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService:
      "B & C Hospital, Birtamode, Jhapa Samarpit Hospital  Phidim",
    phoneNumber: "9806973379",
  },
  {
    name: "Anuradha Acharya/Kumudini",
    specialization: "Masters Clinical Psychology",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Maharjgunj, Chakrapath",
    phoneNumber: "01-4016291",
  },
  {
    name: "Ms. Rama Karki (Adhikari)",
    specialization:
      "MA in Psychology (specialization in children with disabilities)",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Chuchepati",
    phoneNumber: "9841242532",
  },
  {
    name: "Ms. Pujan Sharma",
    specialization: "MA in Clinical Psychology",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Swayambhu, Kathmandu",
    phoneNumber: "01-5247317",
  },
  {
    name: "Dr. Prabhat Sapkota",
    specialization: "MBBS, MD (Psychiatry)",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Nisarga Hospital, Dhangadi - 5, Hasanpur, Kailali",
    phoneNumber: "091-526681",
  },
  {
    name: "Dr. Khagendra Kafle",
    specialization: "MD, Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Maula kalika Hospital, Bharatpur, Chitwan",
    email: "khagendrakafle@gmail.com",
    phoneNumber: "056-526738",
  },
  {
    name: "Dr. Tanveer Ahmed Khan",
    specialization: "MBBS, MD Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService:
      "Amaan Medical Hall, infront of industraial area, Nepalgunj",
    phoneNumber: "081-525994",
  },
  {
    name: "Dr. Tanveer Ahmed Khan",
    specialization: "MBBS, MD Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService:
      "Amaan Medical Hall, infront of industraial area, Nepalgunj",
    phoneNumber: "081-525994",
  },
  {
    name: "Dr. Anoop Krishna Gupta",
    specialization: "MD Psychiatry",
    isOrganization: false,
    category: "Psychotherapy",
    locationofService: "Birta, Birgunj - 5",
    phoneNumber: "9855026050",
  },
  {
    name: "Tranquility Hospital and Research Centre",
    specialization: "Specialist Neuro-psychiatric Hospital",
    isOrganization: true,
    category: "Residental Centre",
    OpeningHours: "24 hours Emergency",
    location: "Khumaltar Oralo, Lalitpur",
    email: "info.tranquilityhospital@gmail.com",
    phoneNumber: "9841504122",
  },
  {
    name: "TPO Nepal",
    specialization: "Physchosocial Mental Health Service",
    isOrganization: true,
    category: "Hotline",
    OpeningHours: "9am - 5pm Monday - Friday",
    location: "Baluwatar, Kathmandu",
    email: "tponepal@tponepal.org",
    phoneNumber: "014431717",
    "toll free": "16600102005 10-4",
  },
  {
    name: "Tranquility Hospital and Research Centre",
    specialization: "Specialist Neuro-psychiatric Hospital",
    isOrganization: true,
    category: "Clinical Care",
    OpeningHours: "24 hours Emergency",
    location: "Khumaltar Oralo, Lalitpur",
    email: "info.tranquilityhospital@gmail.com",
    phoneNumber: "9841504122",
  },
  {
    name: "Dr Sagun Ballav Pant",
    specialization: "MD Psychiatry",
    isOrganization: false,
    category: "Clinical Care",
    locationofService: "Institute of Medicine, TU Teaching Hospital",
    email: "sagum055@gmail.com",
    phoneNumber: "9841444410",
  },
  {
    name: "Subash Chandra Sharma",
    specialization: "MPhil/Clinical Psychologist/CBT",
    isOrganization: false,
    category: "Clinical Care",
    locationofService: "Katyayani Marg, Near Katyayani Temple",
    phoneNumber: "980202977",
  },
  {
    name: "Centre for Mental Health & Counselling - Nepal (CMC-Nepal)",
    specialization: "Mental Health and Psychosocial Service",
    isOrganization: true,
    category: "Clinical Care",
    OpeningHours: "Sunday - Friday by appointment",
    location: "Thapathali Heights, Kathmandu",
    email: "cmcnepal@mos.com.np",
    phoneNumber: "4102037",
  },
  {
    name: "Psychbigyaan Network Nepal - PNN",
    specialization: "Mental Health",
    isOrganization: true,
    category: "Clinical Care",
    OpeningHours: "11:30 am - 6:00 pm from Monday - Saturday",
    location: ["Dhobighat", "Lalitpur"],
    phoneNumber: "9860937293",
  },
];
module.exports = organizations;
